# Identifying/contact information.
name:    thehalfyak
baseurl: chiragbharadwaj.github.io
url:     https://www.thehalfyak.pro
github:  https://github.com/chiragbharadwaj/chiragbharadwaj.github.io

# Markdown configuration (using `kramdown` instead of `rdiscount`).
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  entity_output: symbolic
  math_engine: katex
highlighter: rouge

# Files and directories to include/exclude when building the static site.
include:
  - _assets
  - _data
exclude:
  - .gitignore
  - CNAME

# Default scoping rules for posts/drafts in the blog structure.
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      type: pages
    values:
      permalink: /:path/:basename:output_ext
