# Many of the ideas from this configuration file were borrowed from Adrian
# Sampson, an assistant professor at Cornell University:
#   https://www.cs.cornell.edu/~asampson
#
# Identifying/contact information.
name:     Chirag Bharadwaj
author:   Chirag Bharadwaj
email:    'cb625@cornell.edu'
location: 'Princeton, NJ'
created:  'June 25, 2009'
url:      http://www.chiragbharadwaj.com
base:     ""
github:   https://github.com/chiragbharadwaj
linkedin: https://www.linkedin.com/in/chiragbharadwaj
quora:    https://www.quora.com/profile/Chirag-Bharadwaj

# Markdown configuration (using `kramdown` instead of `rdiscount`).
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  enable_coderay: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  entity_output: symbolic
  math_engine: katex
highlighter: pygments

# Files and directories to exclude when building the static site.
exclude:
  - .gitignore
  - README.md
  - Makefile

# Link style for blog posts.
permalink: /blog/:title.html

# Default scoping rules for posts/drafts in the blog structure.
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
  - scope:
      type: pages
    values:
      permalink: /:path/:basename:output_ext

# Outline of website navigation/file structure.
navigation:
  - title: Home
    link:  http://www.chiragbharadwaj.com/
  - title: About
    link:  http://www.chiragbharadwaj.com/about/
  - title: Blog
    link:  http://blog.chiragbharadwaj.com/
  - title: Misc.
    link:  http://www.chiragbharadwaj.com/misc/
  - title: Contact
    link:  http://www.chiragbharadwaj.com/contact.html

# Drafts of blog posts that will be created/posted in the future...
collections:
  drafts:
    output:    true
    permalink: http://www.chiragbharadwaj.com/blog/drafts/:slug.html
