# Many of the ideas from this configuration file were borrowed from Adrian
# Sampson, an assistant professor at Cornell University:
#   https://www.cs.cornell.edu/~asampson
#
# Identifying/contact information.
name:     Chirag Bharadwaj
author:   Chirag Bharadwaj
email1:   'chiragb@princeton.edu'
email2:   'cb625@cornell.edu'
phone:    '+1 609 937-6050'
skype:    'theRealChiggy'
location: 'Princeton, NJ'
address: 
  - 'Chirag Bharadwaj'
  - '8 Lawrence Drive, Apt. 308'
  - 'Princeton, NJ 08540'
born:     '23 November 1996'
url:      http://www.chiragbharadwaj.com
base:     ""
github:   https://github.com/chiragbharadwaj
linkedin: https://www.linkedin.com/in/chiragbharadwaj

# Markdown configuration (using `kramdown` instead of `rdiscount`).
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  enable_coderay: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  entity_output: symbolic
  math_engine: katex
highlighter: rouge

# Files and directories to exclude when building the static site.
exclude:
  - .gitignore
  - README.md
  - Makefile
  - CNAME

# Link style for blog-style posts.
permalink: /blog/:title.html

# Default scoping rules for posts/drafts in the blog structure.
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
  - scope:
      type: pages
    values:
      permalink: /:path/:basename:output_ext

# Outline of website navigation/file structure.
navigation:
  - title: Home
    link:  /
  - title: About
    link:  /about/
  - title: Research
    link:  /research/
  - title: Blog
    link:  /blog/
  - title: Contact
    link:  /contact/

# Drafts of blog posts that will be created/posted in the future...
collections:
  drafts:
    output:    true
    permalink: /blog/drafts/:slug.html
